package com.example.gabc_.app_fcc.constantes;

public interface Liebermann {

    int LIEBERMANN_RED_MDMA = 8;
    int LIEBERMANN_GREEN_MDMA = 8;
    int LIEBERMANN_BLUE_MDMA = 10;
    String LIEBERMANN_SMDMA = "MDMA";

    int LIEBERMANN_RED_MDE = 8;
    int LIEBERMANN_GREEN_MDE = 8;
    int LIEBERMANN_BLUE_MDE = 10;
    String LIEBERMANN_SMDE = "MDE";

    int LIEBERMANN_RED_SASS = 8;
    int LIEBERMANN_GREEN_SASS = 8;
    int LIEBERMANN_BLUE_SASS = 10;
    String LIEBERMANN_SSASS = "MDA (Sass)";

    int LIEBERMANN_RED_5APB = 8;
    int LIEBERMANN_GREEN_5APB = 8;
    int LIEBERMANN_BLUE_5APB = 10;
    String LIEBERMANN_S5APB = "5-APB";

    int LIEBERMANN_RED_6APB = 8;
    int LIEBERMANN_GREEN_6APB = 8;
    int LIEBERMANN_BLUE_6APB = 10;
    String LIEBERMANN_S6APB = "6-APB";

    int LIEBERMANN_RED_DXM = 8;
    int LIEBERMANN_GREEN_DXM = 8;
    int LIEBERMANN_BLUE_DXM = 10;
    String LIEBERMANN_SDXM = "DXM";

    int LIEBERMANN_RED_ETHYLONE = 8;
    int LIEBERMANN_GREEN_ETHYLONE = 8;
    int LIEBERMANN_BLUE_ETHYLONE = 10;
    String LIEBERMANN_SETHYLONE = "Ethylone";

    int LIEBERMANN_RED_SUGAR = 8;
    int LIEBERMANN_GREEN_SUGAR = 8;
    int LIEBERMANN_BLUE_SUGAR = 10;
    String LIEBERMANN_SSUGAR = "Sugar";

    int LIEBERMANN_RED_METHYLONE = 244;
    int LIEBERMANN_GREEN_METHYLONE = 238;
    int LIEBERMANN_BLUE_METHYLONE = 80;
    String LIEBERMANN_SMETHYLONE = "Methylone";

    int LIEBERMANN_RED_BUTYLONE = 244;
    int LIEBERMANN_GREEN_BUTYLONE = 238;
    int LIEBERMANN_BLUE_BUTYLONE = 80;
    String LIEBERMANN_SBUTYLONE = "Butylone";

    int LIEBERMANN_RED_MDPV = 244;
    int LIEBERMANN_GREEN_MDPV = 238;
    int LIEBERMANN_BLUE_MDPVE = 80;
    String LIEBERMANN_SMDPV = "MDPV";

    int LIEBERMANN_RED_METANPHETAMINE= 223;
    int  LIEBERMANN_GREEN_METANPHETAMINE = 113;
    int LIEBERMANN_BLUE_METANPHETAMINE = 44;
    String LIEBERMANN_SMETAMPHETAMINE = "Metamphetamine / Amphetamine / Mescaline";

    int LIEBERMANN_RED_AMPHETAMINE= 223;
    int  LIEBERMANN_GREEN_AMPHETAMINE = 113;
    int LIEBERMANN_BLUE_AMPHETAMINE = 44;
    String LIEBERMANN_SAMPHETAMINE = "Metamphetamine / Amphetamine / Mescaline";

    int LIEBERMANN_RED_MESCALINE= 223;
    int  LIEBERMANN_GREEN_MESCALINE = 113;
    int LIEBERMANN_BLUE_MESCALINE = 44;
    String LIEBERMANN_S3 = "Metamphetamine / Amphetamine / Mescaline";

    int LIEBERMANN_RED_CODEYNE = 184;
    int LIEBERMANN_GREEN_CODEYNE = 156;
    int LIEBERMANN_BLUE_CODEYNE = 195;
    String LIEBERMANN_SCODEYNE = "Codeyne";

    int LIEBERMANN_RED_MORPHINE = 184;
    int LIEBERMANN_GREEN_MORPHINE = 156;
    int LIEBERMANN_BLUE_MORPHINE = 195;
    String LIEBERMANN_SMORPHINE = "Morphine";

    int LIEBERMANN_RED_OXYCODONE = 184;
    int LIEBERMANN_GREEN_OXYCODONE = 156;
    int LIEBERMANN_BLUE_OXYCODONE = 195;
    String LIEBERMANN_SOXYCODONE = "Oxycodone";

    int LIEBERMANN_RED_ACB = 18;
    int LIEBERMANN_GREEN_ACB = 83;
    int LIEBERMANN_BLUE_ACB = 48;
    String LIEBERMANN_S5 = "aC-B";

    int LIEBERMANN_RED_AC1 = 37;
    int LIEBERMANN_GREEN_AC1 = 70;
    int LIEBERMANN_BLUE_AC1 = 120;
    String LIEBERMANN_SAC1 = "aC-I";

    int LIEBERMANN_RED_HEROIN = 143;
    int LIEBERMANN_GREEN_HEROIN = 27;
    int LIEBERMANN_BLUE_HEROIN = 38;
    String LIEBERMANN_SHEROIN = "Heroin";

    int LIEBERMANN_RED_ASPIRIN = 236;
    int LIEBERMANN_GREEN_ASPIRIN = 43;
    int LIEBERMANN_BLUE_ASPIRIN = 51;
    String LIEBERMANN_SASPIRIN = "Aspirin";

    int LIEBERMANN_REDNR = 180;
    int LIEBERMANN_GREENNR = 151;
    int LIEBERMANN_BLUENR = 120;
    String LIEBERMANN_NR = "SIN REACCIÓN";

}
